### ISSUE TITLE
Feature Request: Add wiredep-like features

### ISSUE THREAD

**Issue by mtraynham** [timmywil/grunt-bowercopy#22]
This library is great!  It would be really cool if it had some added features like wiredep that could automatically hook up the resources into source files, since wiredep doesn't support the copy part.  That way, you don't have to maintain the list of files in two places (grunt config and an index.html).

**Comment by timmywil** [comment]
Thank you for opening an issue, but I'd like to limit the scope of grunt-bowercopy for the meantime.
