### ISSUE TITLE
Why I have to indicate the source files?

### ISSUE THREAD

**Issue by yanni4night** [timmywil/grunt-bowercopy#28]
As I know,the paths of the source file of each bower component should be indicated by _bower.json_,but not hard coded in _Gruntfile.js_.So I should indicate the dest files or dest directory but not the source files in grunt tasks.What do you think of it?

**Comment by zeflasher** [comment]
I have the same question...

**Comment by timmywil** [comment]
Thank you opening an issue, but the answer is that you don't. If the project specifies the files that should be copied using the `main` property in their bower.json, there is already a mechanism for using that instead of writing which files should be copied yourself.

With `:main` pragma...

```js
main: {
  src: 'jquery.panzoom:main',
  dest: 'public/js/plugins/'
}
```
