### ISSUE TITLE
use glob when specifying :main

### ISSUE THREAD

**Issue by lflobo** [timmywil/grunt-bowercopy#33]
Hi!
It's common for developers to specify wildcards in main (ex.: [fontawesome](https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json)).

Keep up the good work.
Thanks in advance,
LL

**Comment by cvrebert** [comment]
A. Bower has now finally specified `main` in greater depth, and deemed wildcards to be invalid; see https://github.com/bower/bower.json-spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99#diff-04c6e90faac2675aa89e2176d2eec7d8R92
B. FontAwesome is working on fixing their `main` to comply with (A); see https://github.com/FortAwesome/Font-Awesome/pull/6227

**Comment by timmywil** [comment]
Thanks @cvrebert!
