### ISSUE TITLE
Rename Files?

### ISSUE THREAD

**Issue by robneu** [timmywil/grunt-bowercopy#34]
This might already be possible, but I can't find a way to do it. Sometimes it would be handy to allow file renaming when the files are copied into place. Maybe exposing it in a way similar to `copyOptions` would be possible?

For reference: 
http://gruntjs.com/api/grunt.file#grunt.file.expandmapping
http://fettblog.eu/blog/2014/05/27/undocumented-features-rename/

**Comment by timmywil** [comment]
Thanks for opening an issue. This happens automatically during the copying process. Simply specify the new name in the destination...

```js
bowercopy: {
     libs: {
         options: {
             destPrefix: 'public/js/libs'
         },
         files: {
             'jquery-renamed.js': 'jquery/dist/jquery.js'
         }
    }
}
```

**Comment by robneu** [comment]
Is this still possible while using a globbing pattern or a directory to copy files?
