### ISSUE TITLE
bowercopy task isn't failing on missing files

### ISSUE THREAD

**Issue by deployable** [timmywil/grunt-bowercopy#35]
Using the following grunt config

```coffeescript
    bowercopy:
      assets:
        options:
          destPrefix: 'assets'
        files:
          'underscore.js':  'underscore/underscore.js'
          'jquery.js':      'jquery/dist/jquery.js'
          'bootstrap.js':   'bootstrap/dist/js/bootstrap.js'
```

When a file before the last file is missing, the task succeeds
```
$ grunt bowercopy:assets
Running "bowercopy:assets" (bowercopy) task
bower_components/underscore/underscore.js -> assets/underscore.js
>> bower_components/jquery/dist/jquery.js was not found
bower_components/bootstrap/dist/js/bootstrap.js -> assets/bootstrap.js

Done, without errors.
```
Personally, I'd expect the task to fail (eventually) if a listed file was missing rather than just a [warning message](https://github.com/timmywil/grunt-bowercopy/blob/4d3f8d8dd7ff5d6527ed76c63961d8b13d139fda/tasks/bowercopy.js#L240)

**Comment by timmywil** [comment]
Thank you for opening an issue. I see where you're coming from, but this has been debated and we came out on the side of warnings. Rather than erroring and stopping all subsequent copies, we opted to do as much work as possible and give warnings.

**Comment by deployable** [comment]
Do you have a link to the discussion? I was searching for the warning specifically but I guess the discussion was before the warning message =).  It would be interesting to see the use cases that people came up with for continuing on errors as I can't see the use of it in this case where specific listed files are missing. 

It's not so bad when a human is running the task but we are using this for an automated task, which I would expect a lot of grunt tasks are, so silent errors are a killer there. 

If it's only the ability to continuing on errors, it's possible to "push" errors and continue until the end. 
If you're not adverse to adding this as an `options` setting at least, I can do up a PR ?

**Comment by timmywil** [comment]
Now that I think about more, the user can just use --force if they want to copy as much as possible. Errors might be the way to go here.
