### ISSUE TITLE
Inject dependencies into HTML

### ISSUE THREAD

**Issue by sepehr** [timmywil/grunt-bowercopy#36]
That would be super-handy if the plugin could optionally manipulate host files (html, php, etc.) and inject the dependencies as configured in `Gruntfile.js`. Like what [wiredep](https://github.com/stephenplusplus/grunt-wiredep) does.

**Comment by timmywil** [comment]
Thank you for the request, but I'd like to keep this plugin as simple as possible. I believe there are other plugins that will inject dependencies from any location, so it shouldn't be too difficult to run bowercopy to place files where you want, then run another plugin to inject them.
