### ISSUE TITLE
Failure without .bowerrc file

### ISSUE THREAD

**Issue by patcamwol** [timmywil/grunt-bowercopy#39]
If there is no .bowerrc file present in the root directory of the project, then the bowercopy task will fail.  This is new behaviour in 1.2.1

**Comment by clawfire** [comment]
Same here. Have to fix the version to `1.2.0` for my deployments

**Comment by juanbrujo** [comment]
having this error today, nothing documented in *Release History*. will downgrade to 1.2.0 a @clawfire says.

**Comment by timmywil** [comment]
Thanks, will release an update today.
