### ISSUE TITLE
:main suffix not working on Windows file system

### ISSUE THREAD

**Issue by hans009** [timmywil/grunt-bowercopy#41]
in bowercopy.js the line 45 contains:
```javascript
var rmain = /^([^:]+):main$/;
```
This doesn't seem to work on windows paths with colons following drive letters. A gruntfile with 
```javascript
files:{
	'./src/main/webapp/libs' : 'bootstrap:main'
}
```
would resolve to a src path for copying *D:\bower_components\bootstrap:main*
The regex failes for such paths: https://regex101.com/r/aO9eZ9/4

This fix would solve the issue (https://regex101.com/r/aO9eZ9/5)
```javascript
var rmain = /^(.+):main$/;
```
(At least for me :-) )

**Comment by deadalusai** [comment]
I've [sent a PR](https://github.com/timmywil/grunt-bowercopy/pull/44) with this exact fix.

**Comment by timmywil** [comment]
Closed by the linked PR.
