### ISSUE TITLE
Option to disable warning when no source files are added yet

### ISSUE THREAD

**Issue by Excolo** [timmywil/grunt-bowercopy#43]
I have a template to create my initial Gruntfiles, and it also adds common bowercopy options. Some of those contain no source files yet, so when I try to build using grunt, I get a warning. I can use -Force, but I really don't want to do that. 

Here's an example. If my grunt template creates the following bowercopy configuration:
```javascript
bowercopy: {
    images: {
        options: { destPrefix: '/images' },
        files: { }
    }
}
```
I get `Warning: Nothing was copied for the "images" target Use --force to continue.`

Is it possible to add an option to disable these warnings, so I can build without necessarily defining source files and instead just ignore that option?

**Comment by timmywil** [comment]
I think the solution is to comment those lines until files are added. Otherwise, there's potential for error. I'd prefer not to add this option.
