### ISSUE TITLE
:main pragma in Windows world

### ISSUE THREAD

**Issue by antonGritsenko** [timmywil/grunt-bowercopy#45]
Hello from Windows world :) Since VS2015 now fully supports Grunt I think will be great to think about Windows world too. Right now there is an issue with Regex rule about :main pragma. It check : before :main. This is not good because in Windows the path can contains:
D:\My Documents\Visual Studio 2015\Projects\Test.MVCProject\Test.MVCProject\lib\bootstrap:main
In this case regex will fail.
Why not to use just ^(.+):main$ ?

**Comment by timmywil** [comment]
I think this has been fixed in master. Could you try that one?

**Comment by antonGritsenko** [comment]
You right! Thanks.

**Comment by timmywil** [comment]
Great, thanks. I'll do a release soon.

**Comment by timmywil** [comment]
Released.
